version: "3.8"

services:
  pg_database:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - "../pg_db_volume:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    networks:
      - pg_network

  pg_admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - pg_network

networks:
  pg_network:
    driver: bridge
